services:
    app:
        container_name: cobalt-instances
        image: codeberg.org/kwiat/instances
        ports:
            - "5000:5000"
        volumes:
            - ./data/:/app/data
            - ./output/:/app/output