services:
    app:
        container_name: cobalt-instances
        build:
            context: .
        ports:
            - "5000:5000"
        volumes:
            - ./output/instances.json:/app/output/instances.json