name: update the website

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'data/**'
      - '.gitea/**'
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: check out this new code
        id: pull
        run: |
          cd ${{ secrets.DIRECTORY }}
          git pull
      - name: docker composure # and it calms you down with dancing fruit videos after docker compose (https://bsky.app/profile/wukko.me/post/3l35kbzmxxs24)
        id: build
        run: |
          cd ${{ secrets.DIRECTORY }}
          sudo docker compose down --volumes
          sudo docker compose up --build -d