name: scan instances

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
    paths:
      - 'data/**'
      - 'scan.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: scan instances
      run: |
        cd ${{ secrets.DIRECTORY }}
        python3 -m pip install commentjson
        python3 scan.py
