name: scan instances

on:
  schedule:
    - cron: '0 * * * *'
  branches:
    - main
  paths:
    - 'data/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: scan instances
      run: |
        cd ${{ secrets.DIRECTORY }}
        python3 scan.py
